version: '3.7'

services:
  project:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - /Users/egorborisov/projects/mlflow_example/mlruns:/Users/egorborisov/projects/mlflow_example/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///Users/egorborisov/projects/mlflow_example/mlruns
    command: >
      mlflow run . --entry-point data-preprocessing --env-manager local
      --experiment-name Cancer_Classification --run-name Data_Preprocessing
      -P test-size=0.4