version: '3.7'

services:
  project:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /Users/egorborisov/projects/mlflow_example/mlruns:/Users/egorborisov/projects/mlflow_example/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///Users/egorborisov/projects/mlflow_example/mlruns
    working_dir: /app
    command: >
      mlserver start .